services:
  - type: web
    name: biriyani-backend
    env: node
    plan: free
    buildCommand: npm install && npm install --workspace=backend --production
    startCommand: node backend/index.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "5000"
